### PR TITLE
Add katversion support and install scripts

### PR DESCRIPTION
**Pull request by ajoubertza**
- Add _katversion_ so that we can get version strings derived from the git version info.  This is required for CAM's automated branch creation tool.
- Install the useful scripts so that they are available on the path.
- Add some more details to setup.py.

Closes issue #14

### CODE REVIEW

**Comment by rubyvanrooyen** [comment]
@ajoubertza I have versions hardcoded in the scripts, should I go through and remove those?

**Comment by ajoubertza** [comment]
@rubyvanrooyen Oh, I see that now.  Yes, I can remove them, or make them report the astrokat version instead.  Which do you prefer?

**Comment by rubyvanrooyen** [comment]
@ajoubertza can we remove the hardcoded values please

**Comment by ajoubertza** [comment]
@rubyvanrooyen Can you have a look at this again, please?

**Pull request merged**
